version: "2"

services:
  python:
    image: registry.gitlab.com/vladtroinich/jupyter_app:latest
    restart: "${RESTART}"
    stdin_open: true
    tty: true
    volumes:
      - jupyter-vol:/source
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ${WORKDIR}:/source
    network_mode: bridge

volumes:
  jupyter-vol:
    driver: local

